module mini_loihi_v8e_ram_wheel_image_top #(
  parameter NEURON_THRESHOLD_INIT = "neuron_threshold.mem",
  parameter NEURON_RESET_INIT = "neuron_reset.mem",
  parameter NEURON_LEAK_INIT = "neuron_leak.mem",
  parameter NEURON_VOLTAGE_INIT = "neuron_voltage.mem",
  parameter AXON_PTR_INIT = "axon_ptr.mem",
  parameter AXON_LEN_INIT = "axon_len.mem",
  parameter BASE_TARGET_INIT = "synapse_target.mem",
  parameter BASE_WEIGHT_INIT = "synapse_weight.mem",
  parameter BASE_DELAY_INIT = "synapse_delay.mem",
  parameter RECURRENT_PTR_INIT = "recurrent_ptr.mem",
  parameter RECURRENT_LEN_INIT = "recurrent_len.mem",
  parameter RECURRENT_TARGET_INIT = "recurrent_target.mem",
  parameter RECURRENT_WEIGHT_INIT = "recurrent_weight.mem",
  parameter RECURRENT_DELAY_INIT = "recurrent_delay.mem"
) (
  input  logic clk,
  input  logic rst,
  output logic init_done,
  input  logic tick_start_valid,
  output logic tick_start_ready,
  input  logic [15:0] tick_id,
  input  logic event_valid,
  output logic event_ready,
  input  logic [7:0] event_axon,
  input  logic [7:0] event_payload,
  input  logic ingress_done_valid,
  output logic ingress_done_ready,
  output logic tick_done_valid,
  input  logic tick_done_ready,
  output logic spike_valid,
  input  logic spike_ready,
  output logic [15:0] spike_tick,
  output logic [7:0] spike_neuron,
  output logic overflow_sticky,
  output logic [3:0] overflow_reason,
  output logic core_error,
  output logic pending_contributions,
  output logic [$clog2(mini_loihi_v8_generated_pkg::POOL_DEPTH+1)-1:0] pool_occupancy,
  output logic [15:0] debug_current_tick,
  output logic [$clog2(mini_loihi_v8_generated_pkg::WHEEL_SLOTS)-1:0] debug_wheel_pointer,
  output logic [4:0] debug_state,
  output logic [31:0] debug_cycle,
  output logic debug_external_accept,
  output logic debug_contribution_insert,
  output logic debug_contribution_consume,
  output logic debug_neuron_update,
  output logic debug_recurrent_expand,
  output logic debug_tick_barrier,
  output logic [31:0] accepted_external_count,
  output logic [31:0] inserted_contribution_count,
  output logic [31:0] consumed_contribution_count,
  output logic [31:0] neuron_update_count,
  output logic [31:0] emitted_spike_count,
  output logic [31:0] recurrent_expansion_count_total,
  output logic [31:0] accumulator_saturation_count,
  output logic [31:0] membrane_saturation_count,
  output logic [31:0] tick_complete_count
);
  mini_loihi_v8e_ram_wheel_core #(
    .NEURON_COUNT(mini_loihi_v8_generated_pkg::NEURON_COUNT),
    .AXON_COUNT(mini_loihi_v8_generated_pkg::AXON_COUNT),
    .BASE_SYNAPSE_COUNT(mini_loihi_v8_generated_pkg::BASE_SYNAPSE_COUNT),
    .RECURRENT_SYNAPSE_COUNT(mini_loihi_v8_generated_pkg::RECURRENT_SYNAPSE_COUNT),
    .MAX_DELAY_TICKS(mini_loihi_v8_generated_pkg::MAX_DELAY_TICKS),
    .WHEEL_SLOTS(mini_loihi_v8_generated_pkg::WHEEL_SLOTS),
    .POOL_DEPTH(mini_loihi_v8_generated_pkg::POOL_DEPTH),
    .SLOT_CAPACITY(mini_loihi_v8_generated_pkg::SLOT_CAPACITY),
    .PER_TARGET_CAPACITY(mini_loihi_v8_generated_pkg::PER_TARGET_CAPACITY),
    .EXTERNAL_FIFO_DEPTH(mini_loihi_v8_generated_pkg::EXTERNAL_FIFO_DEPTH),
    .RECURRENT_SPIKE_DEPTH(mini_loihi_v8_generated_pkg::RECURRENT_SPIKE_DEPTH),
    .EXPANSION_CAPACITY(mini_loihi_v8_generated_pkg::EXPANSION_CAPACITY),
    .PIPELINE_LATENCY(mini_loihi_v8_generated_pkg::PIPELINE_LATENCY),
    .NEURON_THRESHOLD_INIT(NEURON_THRESHOLD_INIT),
    .NEURON_RESET_INIT(NEURON_RESET_INIT),
    .NEURON_LEAK_INIT(NEURON_LEAK_INIT),
    .NEURON_VOLTAGE_INIT(NEURON_VOLTAGE_INIT),
    .AXON_PTR_INIT(AXON_PTR_INIT),
    .AXON_LEN_INIT(AXON_LEN_INIT),
    .BASE_TARGET_INIT(BASE_TARGET_INIT),
    .BASE_WEIGHT_INIT(BASE_WEIGHT_INIT),
    .BASE_DELAY_INIT(BASE_DELAY_INIT),
    .RECURRENT_PTR_INIT(RECURRENT_PTR_INIT),
    .RECURRENT_LEN_INIT(RECURRENT_LEN_INIT),
    .RECURRENT_TARGET_INIT(RECURRENT_TARGET_INIT),
    .RECURRENT_WEIGHT_INIT(RECURRENT_WEIGHT_INIT),
    .RECURRENT_DELAY_INIT(RECURRENT_DELAY_INIT)
  ) core (
    .*,
    .pool_occupancy(pool_occupancy)
  );
endmodule
