"""Public API for the deterministic Mini-Loihi-like architecture simulator."""

from mini_loihi.architecture import (
    MINI_LOIHI_V6_REF,
    CoreArchitectureSpec,
    EventPacketFormatSpec,
    ExecutionSemanticsSpec,
    NumericFormatSpec,
    OverflowMode,
    RoundingMode,
    get_architecture_preset,
)
from mini_loihi.artifacts import architecture_to_dict, validate_compiled_program, write_compiled_artifacts
from mini_loihi.fixed_point import (
    NarrowResult,
    arithmetic_right_shift,
    clamp_to_format,
    fixed_point_multiply,
    move_toward_zero,
    narrow_to_format,
    saturating_add,
    saturating_subtract,
    signed_bounds,
    twos_complement_decode,
    twos_complement_encode,
    unsigned_bounds,
    validate_signed,
    validate_unsigned,
    widening_accumulate,
    wrapping_add,
)
from mini_loihi.benchmark import (
    BenchmarkResult,
    BenchmarkProfile,
    FixedPlasticOverhead,
    MemoryAudit,
    MemoryEstimate,
    SyntheticNetworkConfig,
    TraceOverheadResult,
    audit_memory,
    audit_trace_overhead,
    compare_fixed_vs_plastic,
    default_scale_configs,
    estimate_memory,
    fixed_plastic_overhead,
    generate_synthetic_network,
    run_benchmark,
)
from mini_loihi.core import MiniLoihiCore
from mini_loihi.compiler import compile_network, reconstruct_compiled_connections
from mini_loihi.event import Event, EventQueue
from mini_loihi.export import benchmark_rows, dumps_json, learning_curve_rows, to_plain_data, write_csv_rows, write_json
from mini_loihi.config import CoreConfig
from mini_loihi.memory import NeuronState, NeuronStateMemory, SynapseEntry, SynapseMemory
from mini_loihi.mapping import (
    CoreCapacity,
    CoreMappingReport,
    GlobalConnection,
    MappingReport,
    PartitionedNetwork,
    audit_mapping_round_trip,
    block_partition,
    build_mapping_report,
    map_connections_to_cores,
    reconstruct_global_connections,
    round_robin_partition,
)
from mini_loihi.multicore import (
    CoreTrafficReport,
    EventPacket,
    GlobalNeuronRef,
    LocalAxonRef,
    MultiCoreMetrics,
    MultiCoreProfile,
    MultiCoreSystem,
    RoutingEntry,
    RoutingTable,
)
from mini_loihi.multicore_benchmark import (
    MultiCoreBenchmarkResult,
    run_multicore_benchmark_scenarios,
    run_two_core_feedforward_benchmark,
)
from mini_loihi.hardware_ir import (
    CompilationReport,
    CompiledCoreImage,
    CompiledNeuronPlacement,
    CompiledProgram,
    CompiledRoutingEntry,
    NeuronParameterBanks,
    NeuronStateBanks,
    ResourceUsageReport,
    SourceModelMetadata,
)
from mini_loihi.model_ir import (
    ALIFParameters,
    LIFParameters,
    ConnectionIR,
    InputPortIR,
    LearningRuleKind,
    NetworkIR,
    NeuronModelKind,
    NeuronPopulationIR,
    OutputPortIR,
    network_from_v5_connections,
)
from mini_loihi.pattern_task import (
    DecodeResult,
    LEARNING_PRESETS,
    LearningPreset,
    MicrocircuitTemplate,
    PatternSpec,
    TrainingResult,
    TrialResult,
    assign_reward,
    build_microcircuit_template,
    decode_output_spikes,
    encode_pattern,
    get_learning_preset,
    run_training_experiment,
    run_trial,
)
from mini_loihi.presets import ExperimentPreset, PRESETS, benchmark_config_for_preset, get_preset
from mini_loihi.reference import build_reference_results
from mini_loihi.reference_backend import ReferenceMachine, run_compiled_program, validate_reference_program
from mini_loihi.reference_compatibility import (
    V5CompatibilityReport,
    compare_v5_compatible_subset,
    is_v5_compatible_subset,
)
from mini_loihi.reference_state import (
    ReferenceCoreSnapshot,
    ReferenceCounterSnapshot,
    ReferenceEventType,
    ReferenceInputEvent,
    ReferenceMachineSnapshot,
    ReferencePacket,
    ReferenceRunResult,
    SpikeRecord,
)
from mini_loihi.reference_trace import (
    REFERENCE_TRACE_SCHEMA_VERSION,
    ReferenceTraceRecord,
    trace_json_lines,
    write_reference_trace,
)
from mini_loihi.cycle_backend import CycleDeadlockError, CycleMachine, run_cycle_differential, run_cycle_model
from mini_loihi.cycle_state import (
    CycleMachineSnapshot,
    CycleRunResult,
    DifferentialResult,
    InputPresentationStatus,
    PacketTimingRecord,
)
from mini_loihi.cycle_trace import (
    CYCLE_TRACE_SCHEMA_VERSION,
    CycleTraceRecord,
    cycle_trace_json_lines,
    cycle_trace_sha256,
    write_cycle_trace,
)
from mini_loihi.microarchitecture import (
    MINI_LOIHI_V6_2_REF,
    AccumulatorConflictPolicy,
    ExternalOverflowPolicy,
    IngressArbitrationPolicy,
    MicroarchitectureSpec,
    RouterArbitrationPolicy,
    get_microarchitecture_preset,
)
from mini_loihi.timing_report import CoreTimingReport, CycleTimingReport
from mini_loihi.rtl_artifacts import (
    RTLExportResult,
    RTLSubsetReport,
    export_rtl_fixture,
    generate_rtl_contract_package,
    source_contract_fingerprint,
    validate_checked_in_rtl_contract,
    validate_rtl_event_capacity,
    validate_rtl_subset,
)
from mini_loihi.rtl_config import MINI_LOIHI_V7_0_RTL, RTLProfileSpec, get_rtl_profile
from mini_loihi.rtl_audit import (
    LatencyEvidence,
    StorageEntry,
    ToolGateResult,
    production_top_manifest,
    mempipe_storage_report,
    rtl_audit_report,
    rtl_latency_audit,
    rtl_storage_report,
    run_rtl_gate,
    run_rtl_lint,
    run_rtl_synthesis_report,
)
from mini_loihi.rtl_trace import (
    ParsedRTLOutput,
    RTLCounterRecord,
    RTLNeuronStateRecord,
    RTLSpikeRecord,
    RTLTraceRecord,
    parse_rtl_output,
    rtl_trace_json_lines,
    rtl_trace_sha256,
)
from mini_loihi.rtl_vectors import RTLFixture, build_rtl_demo_fixture, build_seeded_rtl_fixture
from mini_loihi.rtl_verify import (
    RTLRegressionResult,
    RTLToolchain,
    RTLUnitTestResult,
    RTLVerificationResult,
    locate_icarus,
    run_rtl_demo,
    run_rtl_fixture,
    run_rtl_unit_test,
    run_seeded_rtl_regression,
)
from mini_loihi.mempipe_config import (
    MEMPIPE_PROFILE_SCHEMA_VERSION,
    MINI_LOIHI_V7_1B_MEMPIPE,
    MempipeProfileSpec,
    validate_mempipe_profile,
)
from mini_loihi.mempipe_artifacts import (
    MEMPIPE_ARTIFACT_SCHEMA_VERSION,
    MempipeExportResult,
    export_mempipe_fixture,
    generate_mempipe_contract_package,
    mempipe_source_contract_fingerprint,
    validate_mempipe_artifacts,
)
from mini_loihi.mempipe_cycle import MempipeCycleResult, run_mempipe_cycle_oracle
from mini_loihi.mempipe_trace import (
    MEMPIPE_TRACE_SCHEMA_VERSION,
    MempipeInitializationResult,
    MempipeScannerResult,
    MempipeTraceRecord,
    ParsedMempipeOutput,
    mempipe_trace_json_lines,
    mempipe_trace_sha256,
    parse_mempipe_output,
)
from mini_loihi.mempipe_verify import (
    MempipeRegressionResult,
    MempipeVerificationResult,
    compile_mempipe_production,
    run_mempipe_demo,
    run_mempipe_fixture,
    run_seeded_mempipe_regression,
    write_mempipe_trace,
)
from mini_loihi.lifpipe_config import (
    LIFPIPE_PROFILE_SCHEMA_VERSION,
    MINI_LOIHI_V7_1B2_LIFPIPE,
    LifpipeProfileSpec,
    LifpipeStageSpec,
    validate_lifpipe_profile,
)
from mini_loihi.lifpipe_artifacts import (
    LIFPIPE_ARTIFACT_SCHEMA_VERSION,
    LifpipeExportResult,
    export_lifpipe_fixture,
    generate_lifpipe_contract_package,
    lifpipe_source_contract_fingerprint,
    validate_lifpipe_artifacts,
)
from mini_loihi.lifpipe_cycle import LifpipeCycleResult, run_lifpipe_cycle_oracle
from mini_loihi.lifpipe_trace import (
    LIFPIPE_TRACE_SCHEMA_VERSION,
    LifpipeInitialization,
    LifpipeTraceRecord,
    LifpipeUtilization,
    ParsedLifpipeOutput,
    lifpipe_trace_json_lines,
    lifpipe_trace_sha256,
    parse_lifpipe_output,
)
from mini_loihi.lifpipe_verify import (
    LifpipeRegressionResult,
    LifpipeVerificationResult,
    compile_lifpipe_production,
    run_lifpipe_demo,
    run_lifpipe_fixture,
    run_seeded_lifpipe_regression,
    write_lifpipe_trace,
)
from mini_loihi.readycut_config import (
    READYCUT_PROFILE_SCHEMA_VERSION,
    MINI_LOIHI_V7_1D2_READYCUT,
    ReadyCutProfileSpec,
    validate_readycut_profile,
)
from mini_loihi.readycut_artifacts import (
    READYCUT_ARTIFACT_SCHEMA_VERSION,
    ReadyCutExportResult,
    export_readycut_fixture,
    generate_readycut_contract_package,
    readycut_source_contract_fingerprint,
    validate_readycut_artifacts,
)
from mini_loihi.readycut_cycle import ReadyCutCycleResult, run_readycut_cycle_oracle
from mini_loihi.readycut_verify import (
    ReadyCutRegressionResult,
    ReadyCutVerificationResult,
    compile_readycut_production,
    run_readycut_demo,
    run_readycut_fixture,
    run_seeded_readycut_regression,
    write_readycut_trace,
)
from mini_loihi.stability_audit import (
    AuditReport,
    PlasticitySummary,
    PopulationActivitySummary,
    StabilityGuardrails,
    SweepResult,
    TrialDiagnostics,
    WeightSummary,
    classify_stability,
    evaluate_guardrails,
    run_learning_stability_audit,
    summarize_weights,
)
from mini_loihi.trace import Metrics, TraceRecord
from mini_loihi.validation import (
    CoreStateSnapshot,
    DeterminismSnapshot,
    EquivalenceReport,
    run_repeated_multicore_snapshot,
    run_single_partition_equivalence,
    snapshot_core,
)
from mini_loihi.v8_architecture import (
    MINI_LOIHI_V8_0A_RECURRENCE_DELAY,
    V8RecurrenceDelayProfile,
    get_v8_recurrence_delay_profile,
)
from mini_loihi.v8_artifacts import V8ArtifactExportResult, export_v8_artifacts
from mini_loihi.v8_compiler import compile_v8_network
from mini_loihi.v8_examples import build_v8_recurrence_demo
from mini_loihi.v8_hardware_ir import CompiledRecurrentSynapse, V8CompiledProgram
from mini_loihi.v8_model_ir import RecurrentConnectionIR, V8NetworkIR
from mini_loihi.v8_reference import (
    V8ReferenceCounters,
    V8ReferenceMachine,
    V8ReferenceResult,
    V8RoutedEvent,
    V8ScheduledContribution,
    V8Spike,
    V8TraceRecord,
    run_v8_reference,
    v8_trace_json_lines,
)
from mini_loihi.v8_cycle_backend import (
    V8DelayWheelMachine,
    compile_v8_cycle_network,
    run_v8_cycle_differential,
    run_v8_cycle_model,
    validate_v8_cycle_program,
    v8_cycle_trace_json_lines,
)
from mini_loihi.v8_cycle_profile import (
    DEFAULT_V8_CYCLE_PROFILE,
    V8_CYCLE_BALANCED_255,
    V8_CYCLE_EXTENDED_1023,
    V8_CYCLE_PROFILES,
    V8_CYCLE_SMALL_63,
    V8CycleProfile,
    get_v8_cycle_profile,
)
from mini_loihi.v8_cycle_resources import (
    V8CycleResourceEstimate,
    V8CycleThroughputEstimate,
    build_v8_profile_evaluation,
    estimate_v8_cycle_resources,
    estimate_v8_cycle_throughput,
)
from mini_loihi.v8_cycle_state import (
    V8CycleCapacityError,
    V8CycleCounters,
    V8CycleDifferentialResult,
    V8CycleResult,
    V8CycleTraceRecord,
)
from mini_loihi.v8_rtl_artifacts import V8RTLExportResult, export_v8_rtl_fixture
from mini_loihi.v8_rtl_config import MINI_LOIHI_V8_0C_RTL, V8RTLProfileSpec, get_v8_rtl_profile
from mini_loihi.v8_rtl_eda import run_v8_rtl_eda
from mini_loihi.v8_rtl_reports import (
    FROZEN_V8_0C_BASELINE,
    build_v8_rtl_demo_report,
    build_v8_rtl_regression_report,
    build_v8_rtl_resource_report,
    write_v8_rtl_reports,
)
from mini_loihi.v8_rtl_vectors import build_seeded_v8_rtl_fixture, build_v8_rtl_regression_fixtures
from mini_loihi.v8_rtl_verify import (
    V8RTLRegressionResult,
    V8RTLTraceRecord,
    V8RTLVerificationResult,
    compile_v8_rtl_production,
    run_v8_rtl_fixture,
    run_v8_rtl_regression,
)
from mini_loihi.v8e_cycle_backend import (
    V8E_RAM_CYCLE_PROFILE,
    V8ERAMCycleDifferential,
    V8ERAMDelayWheelMachine,
    run_v8e_ram_cycle_differential,
    run_v8e_ram_cycle_model,
)
from mini_loihi.v8e_eda import run_v8e_eda
from mini_loihi.v8e_reports import (
    FROZEN_V8_0E_BASELINE,
    build_v8e_demo_report,
    build_v8e_diagnosis_report,
    build_v8e_regression_report,
    build_v8e_resource_report,
    frozen_v8c_files_match,
    write_v8e_reports,
)
from mini_loihi.v8e_rtl_verify import (
    V8ERTLResult,
    compile_v8e_rtl_production,
    run_v8e_rtl_expected_overflow,
    run_v8e_rtl_fixture,
    run_v8e_rtl_reset_check,
    v8e_rtl_source_fingerprint,
)
from mini_loihi.v81_artifacts import V81ArtifactExportResult, export_v81_artifacts
from mini_loihi.v81_compiler import compile_v81_network
from mini_loihi.v81_examples import build_v81_alif_demo
from mini_loihi.v81_hardware_ir import V81CompiledProgram, V81CompiledRecurrentSynapse
from mini_loihi.v81_model_ir import (
    CANONICAL_V81_TEMPLATES,
    NeuronTypeKind,
    SynapseTypeKind,
    V81ConnectionIR,
    V81NetworkIR,
    V81NeuronPopulationIR,
    V81NeuronTemplate,
    V81RecurrentConnectionIR,
)
from mini_loihi.v81_reference import (
    V81ReferenceCounters,
    V81ReferenceMachine,
    V81ReferenceResult,
    V81TraceRecord,
    run_v81_reference,
    v81_trace_json_lines,
)
from mini_loihi.v81_reports import FROZEN_V8_1A_BASELINE, build_v81_reference_report, write_v81_reports
from mini_loihi.v81_cycle_backend import (
    V81NeuronCycleMachine,
    run_v81_cycle_differential,
    run_v81_cycle_model,
    validate_v81_cycle_program,
    v81_cycle_trace_json_lines,
)
from mini_loihi.v81_cycle_profile import (
    DEFAULT_V81_CYCLE_PROFILE,
    V81_CYCLE_DUAL,
    V81_CYCLE_PROFILES,
    V81_CYCLE_SHARED,
    V81_CYCLE_SHIFT_ADD,
    V81CycleMemorySpec,
    V81CycleProfile,
    build_v81_memory_specs,
    get_v81_cycle_profile,
)
from mini_loihi.v81_cycle_reports import (
    FROZEN_V8_1B_BASELINE,
    build_v81_cycle_demo_report,
    build_v81_cycle_regression_report,
    write_v81_cycle_reports,
)
from mini_loihi.v81_cycle_resources import (
    V81ArithmeticEstimate,
    V81CycleResourceEstimate,
    V81WorkloadEstimate,
    build_v81_resource_report,
    estimate_v81_arithmetic,
    estimate_v81_cycle_resources,
    estimate_v81_workload,
)
from mini_loihi.v81_cycle_contract import (
    run_v81_cycle_contract,
    v81_contract_trace_sha256,
    v81_wheel_lane_fsm_states,
)
from mini_loihi.v81_cycle_state import (
    V81CycleCapacityError,
    V81CycleContractRecord,
    V81CycleContractResult,
    V81CycleCounters,
    V81CycleDifferentialResult,
    V81CycleNeuronUpdate,
    V81CycleResult,
    V81CycleTraceRecord,
)
from mini_loihi.v81_cycle_vectors import build_seeded_v81_cycle_case
from mini_loihi.v9_architecture import MINI_LOIHI_V9_0A_THREE_FACTOR, V9_PROFILE_IDENTIFIER
from mini_loihi.v9_artifacts import V9ArtifactExportResult, export_v9_artifacts
from mini_loihi.v9_compiler import compile_v9_network
from mini_loihi.v9_dense_oracle import V9DenseOracle, V9DifferentialResult, compare_v9_backends, run_v9_dense_oracle
from mini_loihi.v9_examples import build_v9_alif_recurrence_demo, build_v9_delayed_reward_demo, build_v9_reward_sign_demo
from mini_loihi.v9_hardware_ir import V9CompiledProgram, V9CompiledSynapse
from mini_loihi.v9_model_ir import V9ModulationEvent, V9NetworkIR, V9PlasticityRuleIR, V9ResetPolicy
from mini_loihi.v9_reference import V9LearningTraceRecord, V9ReferenceMachine, V9ReferenceResult, run_v9_reference, v9_learning_trace_json_lines
from mini_loihi.v9_reports import build_v9_demo_report, write_v9_reports
from mini_loihi.v9_random import build_seeded_v9_learning_case, build_v9_random_differential_report

__all__ = [
    "ALIFParameters",
    "BenchmarkResult",
    "BenchmarkProfile",
    "CoreCapacity",
    "CoreArchitectureSpec",
    "CoreMappingReport",
    "CoreConfig",
    "CoreStateSnapshot",
    "CoreTrafficReport",
    "CompilationReport",
    "CompiledCoreImage",
    "CompiledNeuronPlacement",
    "CompiledProgram",
    "CompiledRoutingEntry",
    "ConnectionIR",
    "DecodeResult",
    "DeterminismSnapshot",
    "EquivalenceReport",
    "Event",
    "EventQueue",
    "EventPacket",
    "EventPacketFormatSpec",
    "ExperimentPreset",
    "FixedPlasticOverhead",
    "GlobalConnection",
    "GlobalNeuronRef",
    "LEARNING_PRESETS",
    "LIFParameters",
    "LearningRuleKind",
    "LearningPreset",
    "LocalAxonRef",
    "Metrics",
    "MiniLoihiCore",
    "MultiCoreMetrics",
    "MultiCoreProfile",
    "MultiCoreSystem",
    "MultiCoreBenchmarkResult",
    "MemoryEstimate",
    "MemoryAudit",
    "MappingReport",
    "MicrocircuitTemplate",
    "MINI_LOIHI_V6_REF",
    "NetworkIR",
    "NarrowResult",
    "NeuronModelKind",
    "NeuronParameterBanks",
    "NeuronPopulationIR",
    "NeuronStateBanks",
    "NeuronState",
    "NeuronStateMemory",
    "PatternSpec",
    "PartitionedNetwork",
    "PlasticitySummary",
    "PopulationActivitySummary",
    "PRESETS",
    "OverflowMode",
    "OutputPortIR",
    "RoutingEntry",
    "RoutingTable",
    "RoundingMode",
    "ResourceUsageReport",
    "REFERENCE_TRACE_SCHEMA_VERSION",
    "ReferenceCoreSnapshot",
    "ReferenceCounterSnapshot",
    "ReferenceEventType",
    "ReferenceInputEvent",
    "ReferenceMachine",
    "ReferenceMachineSnapshot",
    "ReferencePacket",
    "ReferenceRunResult",
    "ReferenceTraceRecord",
    "StabilityGuardrails",
    "SynapseEntry",
    "SynapseMemory",
    "SourceModelMetadata",
    "SyntheticNetworkConfig",
    "SweepResult",
    "SpikeRecord",
    "TraceOverheadResult",
    "TraceRecord",
    "TrainingResult",
    "TrialResult",
    "TrialDiagnostics",
    "WeightSummary",
    "V5CompatibilityReport",
    "ExecutionSemanticsSpec",
    "InputPortIR",
    "NumericFormatSpec",
    "assign_reward",
    "audit_memory",
    "audit_mapping_round_trip",
    "audit_trace_overhead",
    "architecture_to_dict",
    "arithmetic_right_shift",
    "benchmark_config_for_preset",
    "benchmark_rows",
    "block_partition",
    "build_mapping_report",
    "build_microcircuit_template",
    "build_reference_results",
    "classify_stability",
    "compare_fixed_vs_plastic",
    "compare_v5_compatible_subset",
    "compile_network",
    "clamp_to_format",
    "default_scale_configs",
    "decode_output_spikes",
    "dumps_json",
    "encode_pattern",
    "estimate_memory",
    "evaluate_guardrails",
    "fixed_plastic_overhead",
    "fixed_point_multiply",
    "generate_synthetic_network",
    "get_learning_preset",
    "get_architecture_preset",
    "get_preset",
    "learning_curve_rows",
    "map_connections_to_cores",
    "move_toward_zero",
    "narrow_to_format",
    "network_from_v5_connections",
    "reconstruct_global_connections",
    "round_robin_partition",
    "reconstruct_compiled_connections",
    "run_benchmark",
    "run_compiled_program",
    "run_learning_stability_audit",
    "run_multicore_benchmark_scenarios",
    "run_repeated_multicore_snapshot",
    "run_single_partition_equivalence",
    "run_training_experiment",
    "run_trial",
    "run_two_core_feedforward_benchmark",
    "snapshot_core",
    "saturating_add",
    "saturating_subtract",
    "signed_bounds",
    "summarize_weights",
    "to_plain_data",
    "trace_json_lines",
    "twos_complement_decode",
    "twos_complement_encode",
    "unsigned_bounds",
    "validate_reference_program",
    "validate_signed",
    "validate_unsigned",
    "widening_accumulate",
    "wrapping_add",
    "write_csv_rows",
    "validate_compiled_program",
    "write_compiled_artifacts",
    "write_reference_trace",
    "write_json",
    "is_v5_compatible_subset",
    "AccumulatorConflictPolicy",
    "CYCLE_TRACE_SCHEMA_VERSION",
    "CoreTimingReport",
    "CycleDeadlockError",
    "CycleMachine",
    "CycleMachineSnapshot",
    "CycleRunResult",
    "CycleTimingReport",
    "CycleTraceRecord",
    "DifferentialResult",
    "ExternalOverflowPolicy",
    "IngressArbitrationPolicy",
    "InputPresentationStatus",
    "MINI_LOIHI_V6_2_REF",
    "MicroarchitectureSpec",
    "PacketTimingRecord",
    "RouterArbitrationPolicy",
    "cycle_trace_json_lines",
    "cycle_trace_sha256",
    "get_microarchitecture_preset",
    "run_cycle_differential",
    "run_cycle_model",
    "write_cycle_trace",
    "MINI_LOIHI_V7_0_RTL",
    "ParsedRTLOutput",
    "RTLCounterRecord",
    "RTLExportResult",
    "RTLFixture",
    "RTLNeuronStateRecord",
    "RTLProfileSpec",
    "RTLRegressionResult",
    "RTLSpikeRecord",
    "RTLSubsetReport",
    "RTLToolchain",
    "RTLTraceRecord",
    "RTLUnitTestResult",
    "RTLVerificationResult",
    "LatencyEvidence",
    "StorageEntry",
    "ToolGateResult",
    "build_rtl_demo_fixture",
    "build_seeded_rtl_fixture",
    "export_rtl_fixture",
    "generate_rtl_contract_package",
    "get_rtl_profile",
    "locate_icarus",
    "parse_rtl_output",
    "rtl_trace_json_lines",
    "rtl_trace_sha256",
    "run_rtl_demo",
    "run_rtl_fixture",
    "run_rtl_unit_test",
    "run_seeded_rtl_regression",
    "production_top_manifest",
    "mempipe_storage_report",
    "rtl_audit_report",
    "rtl_latency_audit",
    "rtl_storage_report",
    "run_rtl_gate",
    "run_rtl_lint",
    "run_rtl_synthesis_report",
    "source_contract_fingerprint",
    "validate_rtl_subset",
    "validate_checked_in_rtl_contract",
    "validate_rtl_event_capacity",
    "MEMPIPE_PROFILE_SCHEMA_VERSION",
    "MEMPIPE_ARTIFACT_SCHEMA_VERSION",
    "MEMPIPE_TRACE_SCHEMA_VERSION",
    "MINI_LOIHI_V7_1B_MEMPIPE",
    "MempipeProfileSpec",
    "MempipeExportResult",
    "MempipeCycleResult",
    "MempipeInitializationResult",
    "MempipeScannerResult",
    "MempipeTraceRecord",
    "ParsedMempipeOutput",
    "MempipeRegressionResult",
    "MempipeVerificationResult",
    "validate_mempipe_profile",
    "export_mempipe_fixture",
    "generate_mempipe_contract_package",
    "mempipe_source_contract_fingerprint",
    "validate_mempipe_artifacts",
    "run_mempipe_cycle_oracle",
    "parse_mempipe_output",
    "mempipe_trace_json_lines",
    "mempipe_trace_sha256",
    "compile_mempipe_production",
    "run_mempipe_demo",
    "run_mempipe_fixture",
    "run_seeded_mempipe_regression",
    "write_mempipe_trace",
    "LIFPIPE_PROFILE_SCHEMA_VERSION",
    "LIFPIPE_ARTIFACT_SCHEMA_VERSION",
    "LIFPIPE_TRACE_SCHEMA_VERSION",
    "MINI_LOIHI_V7_1B2_LIFPIPE",
    "LifpipeProfileSpec",
    "LifpipeStageSpec",
    "LifpipeExportResult",
    "LifpipeCycleResult",
    "LifpipeInitialization",
    "LifpipeTraceRecord",
    "LifpipeUtilization",
    "ParsedLifpipeOutput",
    "LifpipeRegressionResult",
    "LifpipeVerificationResult",
    "validate_lifpipe_profile",
    "export_lifpipe_fixture",
    "generate_lifpipe_contract_package",
    "lifpipe_source_contract_fingerprint",
    "validate_lifpipe_artifacts",
    "run_lifpipe_cycle_oracle",
    "parse_lifpipe_output",
    "lifpipe_trace_json_lines",
    "lifpipe_trace_sha256",
    "compile_lifpipe_production",
    "run_lifpipe_demo",
    "run_lifpipe_fixture",
    "run_seeded_lifpipe_regression",
    "write_lifpipe_trace",
    "READYCUT_PROFILE_SCHEMA_VERSION",
    "READYCUT_ARTIFACT_SCHEMA_VERSION",
    "MINI_LOIHI_V7_1D2_READYCUT",
    "ReadyCutProfileSpec",
    "ReadyCutExportResult",
    "ReadyCutCycleResult",
    "ReadyCutRegressionResult",
    "ReadyCutVerificationResult",
    "validate_readycut_profile",
    "export_readycut_fixture",
    "generate_readycut_contract_package",
    "readycut_source_contract_fingerprint",
    "validate_readycut_artifacts",
    "run_readycut_cycle_oracle",
    "compile_readycut_production",
    "run_readycut_demo",
    "run_readycut_fixture",
    "run_seeded_readycut_regression",
    "write_readycut_trace",
    "MINI_LOIHI_V8_0A_RECURRENCE_DELAY",
    "V8RecurrenceDelayProfile",
    "V8ArtifactExportResult",
    "CompiledRecurrentSynapse",
    "V8CompiledProgram",
    "RecurrentConnectionIR",
    "V8NetworkIR",
    "V8ReferenceCounters",
    "V8ReferenceMachine",
    "V8ReferenceResult",
    "V8RoutedEvent",
    "V8ScheduledContribution",
    "V8Spike",
    "V8TraceRecord",
    "build_v8_recurrence_demo",
    "compile_v8_network",
    "export_v8_artifacts",
    "get_v8_recurrence_delay_profile",
    "run_v8_reference",
    "v8_trace_json_lines",
    "DEFAULT_V8_CYCLE_PROFILE",
    "V8_CYCLE_BALANCED_255",
    "V8_CYCLE_EXTENDED_1023",
    "V8_CYCLE_PROFILES",
    "V8_CYCLE_SMALL_63",
    "V8CycleProfile",
    "V8CycleCapacityError",
    "V8CycleCounters",
    "V8CycleDifferentialResult",
    "V8CycleResourceEstimate",
    "V8CycleResult",
    "V8CycleThroughputEstimate",
    "V8CycleTraceRecord",
    "V8DelayWheelMachine",
    "build_v8_profile_evaluation",
    "compile_v8_cycle_network",
    "estimate_v8_cycle_resources",
    "estimate_v8_cycle_throughput",
    "get_v8_cycle_profile",
    "run_v8_cycle_differential",
    "run_v8_cycle_model",
    "validate_v8_cycle_program",
    "v8_cycle_trace_json_lines",
    "MINI_LOIHI_V8_0C_RTL",
    "V8RTLExportResult",
    "V8RTLProfileSpec",
    "V8RTLRegressionResult",
    "V8RTLTraceRecord",
    "V8RTLVerificationResult",
    "FROZEN_V8_0C_BASELINE",
    "build_seeded_v8_rtl_fixture",
    "build_v8_rtl_demo_report",
    "build_v8_rtl_regression_fixtures",
    "build_v8_rtl_regression_report",
    "build_v8_rtl_resource_report",
    "compile_v8_rtl_production",
    "export_v8_rtl_fixture",
    "get_v8_rtl_profile",
    "run_v8_rtl_eda",
    "run_v8_rtl_fixture",
    "run_v8_rtl_regression",
    "write_v8_rtl_reports",
    "V8E_RAM_CYCLE_PROFILE",
    "V8ERAMCycleDifferential",
    "V8ERAMDelayWheelMachine",
    "V8ERTLResult",
    "FROZEN_V8_0E_BASELINE",
    "build_v8e_demo_report",
    "build_v8e_diagnosis_report",
    "build_v8e_regression_report",
    "build_v8e_resource_report",
    "compile_v8e_rtl_production",
    "frozen_v8c_files_match",
    "run_v8e_eda",
    "run_v8e_ram_cycle_differential",
    "run_v8e_ram_cycle_model",
    "run_v8e_rtl_expected_overflow",
    "run_v8e_rtl_fixture",
    "run_v8e_rtl_reset_check",
    "v8e_rtl_source_fingerprint",
    "write_v8e_reports",
    "CANONICAL_V81_TEMPLATES",
    "FROZEN_V8_1A_BASELINE",
    "NeuronTypeKind",
    "SynapseTypeKind",
    "V81ArtifactExportResult",
    "V81CompiledProgram",
    "V81CompiledRecurrentSynapse",
    "V81ConnectionIR",
    "V81NetworkIR",
    "V81NeuronPopulationIR",
    "V81NeuronTemplate",
    "V81RecurrentConnectionIR",
    "V81ReferenceCounters",
    "V81ReferenceMachine",
    "V81ReferenceResult",
    "V81TraceRecord",
    "build_v81_alif_demo",
    "build_v81_reference_report",
    "compile_v81_network",
    "export_v81_artifacts",
    "run_v81_reference",
    "v81_trace_json_lines",
    "write_v81_reports",
    "DEFAULT_V81_CYCLE_PROFILE",
    "FROZEN_V8_1B_BASELINE",
    "V81ArithmeticEstimate",
    "V81CycleCapacityError",
    "V81CycleCounters",
    "V81CycleContractRecord",
    "V81CycleContractResult",
    "V81CycleDifferentialResult",
    "V81CycleMemorySpec",
    "V81CycleNeuronUpdate",
    "V81CycleProfile",
    "V81CycleResourceEstimate",
    "V81CycleResult",
    "V81CycleTraceRecord",
    "V81NeuronCycleMachine",
    "V81WorkloadEstimate",
    "V81_CYCLE_DUAL",
    "V81_CYCLE_PROFILES",
    "V81_CYCLE_SHARED",
    "V81_CYCLE_SHIFT_ADD",
    "build_seeded_v81_cycle_case",
    "build_v81_cycle_demo_report",
    "build_v81_cycle_regression_report",
    "build_v81_memory_specs",
    "build_v81_resource_report",
    "estimate_v81_arithmetic",
    "estimate_v81_cycle_resources",
    "estimate_v81_workload",
    "get_v81_cycle_profile",
    "run_v81_cycle_differential",
    "run_v81_cycle_contract",
    "run_v81_cycle_model",
    "validate_v81_cycle_program",
    "v81_cycle_trace_json_lines",
    "v81_contract_trace_sha256",
    "v81_wheel_lane_fsm_states",
    "write_v81_cycle_reports",
    "MINI_LOIHI_V9_0A_THREE_FACTOR",
    "V9_PROFILE_IDENTIFIER",
    "V9ArtifactExportResult",
    "V9CompiledProgram",
    "V9CompiledSynapse",
    "V9DenseOracle",
    "V9DifferentialResult",
    "V9LearningTraceRecord",
    "V9ModulationEvent",
    "V9NetworkIR",
    "V9PlasticityRuleIR",
    "V9ReferenceMachine",
    "V9ReferenceResult",
    "V9ResetPolicy",
    "build_v9_alif_recurrence_demo",
    "build_v9_delayed_reward_demo",
    "build_v9_demo_report",
    "build_v9_reward_sign_demo",
    "compare_v9_backends",
    "compile_v9_network",
    "export_v9_artifacts",
    "run_v9_dense_oracle",
    "run_v9_reference",
    "v9_learning_trace_json_lines",
    "write_v9_reports",
    "build_seeded_v9_learning_case",
    "build_v9_random_differential_report",
]
