"""Public API for the deterministic Mini-Loihi-like architecture simulator."""

from mini_loihi.benchmark import (
    BenchmarkResult,
    BenchmarkProfile,
    FixedPlasticOverhead,
    MemoryAudit,
    MemoryEstimate,
    SyntheticNetworkConfig,
    TraceOverheadResult,
    audit_memory,
    audit_trace_overhead,
    compare_fixed_vs_plastic,
    default_scale_configs,
    estimate_memory,
    fixed_plastic_overhead,
    generate_synthetic_network,
    run_benchmark,
)
from mini_loihi.core import MiniLoihiCore
from mini_loihi.event import Event, EventQueue
from mini_loihi.export import benchmark_rows, dumps_json, learning_curve_rows, to_plain_data, write_csv_rows, write_json
from mini_loihi.config import CoreConfig
from mini_loihi.memory import NeuronState, NeuronStateMemory, SynapseEntry, SynapseMemory
from mini_loihi.mapping import (
    CoreCapacity,
    CoreMappingReport,
    GlobalConnection,
    MappingReport,
    PartitionedNetwork,
    audit_mapping_round_trip,
    block_partition,
    build_mapping_report,
    map_connections_to_cores,
    reconstruct_global_connections,
    round_robin_partition,
)
from mini_loihi.multicore import (
    CoreTrafficReport,
    EventPacket,
    GlobalNeuronRef,
    LocalAxonRef,
    MultiCoreMetrics,
    MultiCoreProfile,
    MultiCoreSystem,
    RoutingEntry,
    RoutingTable,
)
from mini_loihi.multicore_benchmark import (
    MultiCoreBenchmarkResult,
    run_multicore_benchmark_scenarios,
    run_two_core_feedforward_benchmark,
)
from mini_loihi.pattern_task import (
    DecodeResult,
    LEARNING_PRESETS,
    LearningPreset,
    MicrocircuitTemplate,
    PatternSpec,
    TrainingResult,
    TrialResult,
    assign_reward,
    build_microcircuit_template,
    decode_output_spikes,
    encode_pattern,
    get_learning_preset,
    run_training_experiment,
    run_trial,
)
from mini_loihi.presets import ExperimentPreset, PRESETS, benchmark_config_for_preset, get_preset
from mini_loihi.reference import build_reference_results
from mini_loihi.stability_audit import (
    AuditReport,
    PlasticitySummary,
    PopulationActivitySummary,
    StabilityGuardrails,
    SweepResult,
    TrialDiagnostics,
    WeightSummary,
    classify_stability,
    evaluate_guardrails,
    run_learning_stability_audit,
    summarize_weights,
)
from mini_loihi.trace import Metrics, TraceRecord
from mini_loihi.validation import (
    CoreStateSnapshot,
    DeterminismSnapshot,
    EquivalenceReport,
    run_repeated_multicore_snapshot,
    run_single_partition_equivalence,
    snapshot_core,
)

__all__ = [
    "BenchmarkResult",
    "BenchmarkProfile",
    "CoreCapacity",
    "CoreMappingReport",
    "CoreConfig",
    "CoreStateSnapshot",
    "CoreTrafficReport",
    "DecodeResult",
    "DeterminismSnapshot",
    "EquivalenceReport",
    "Event",
    "EventQueue",
    "EventPacket",
    "ExperimentPreset",
    "FixedPlasticOverhead",
    "GlobalConnection",
    "GlobalNeuronRef",
    "LEARNING_PRESETS",
    "LearningPreset",
    "LocalAxonRef",
    "Metrics",
    "MiniLoihiCore",
    "MultiCoreMetrics",
    "MultiCoreProfile",
    "MultiCoreSystem",
    "MultiCoreBenchmarkResult",
    "MemoryEstimate",
    "MemoryAudit",
    "MappingReport",
    "MicrocircuitTemplate",
    "NeuronState",
    "NeuronStateMemory",
    "PatternSpec",
    "PartitionedNetwork",
    "PlasticitySummary",
    "PopulationActivitySummary",
    "PRESETS",
    "RoutingEntry",
    "RoutingTable",
    "StabilityGuardrails",
    "SynapseEntry",
    "SynapseMemory",
    "SyntheticNetworkConfig",
    "SweepResult",
    "TraceOverheadResult",
    "TraceRecord",
    "TrainingResult",
    "TrialResult",
    "TrialDiagnostics",
    "WeightSummary",
    "assign_reward",
    "audit_memory",
    "audit_mapping_round_trip",
    "audit_trace_overhead",
    "benchmark_config_for_preset",
    "benchmark_rows",
    "block_partition",
    "build_mapping_report",
    "build_microcircuit_template",
    "build_reference_results",
    "classify_stability",
    "compare_fixed_vs_plastic",
    "default_scale_configs",
    "decode_output_spikes",
    "dumps_json",
    "encode_pattern",
    "estimate_memory",
    "evaluate_guardrails",
    "fixed_plastic_overhead",
    "generate_synthetic_network",
    "get_learning_preset",
    "get_preset",
    "learning_curve_rows",
    "map_connections_to_cores",
    "reconstruct_global_connections",
    "round_robin_partition",
    "run_benchmark",
    "run_learning_stability_audit",
    "run_multicore_benchmark_scenarios",
    "run_repeated_multicore_snapshot",
    "run_single_partition_equivalence",
    "run_training_experiment",
    "run_trial",
    "run_two_core_feedforward_benchmark",
    "snapshot_core",
    "summarize_weights",
    "to_plain_data",
    "write_csv_rows",
    "write_json",
]
